[build]
  functions = "backend/functions"
  publish = "frontend/dist"
  command = "cd frontend && npm run build"

[dev]
  port = 8888
  functions = "backend/functions"
  framework= "vite"
  command = "npm run client"